oss_fuzz_path: ./oss-fuzz
decompilers:
  - "angr"
  - "binja"
  - "dewolf"
  - "ghidra"
  - "hexrays"
  - "mlm"
  - "retdec"
  - "llm4decompile"
  - "qwen"
  - "deepseek"
  - "gpt-4o-mini"
  - "gpt-4o"
  - "claude"
  - "func"
opts:
  - O0
  - O1
  - O2
  - O3
  - Os
